name: Feature Request
description: Suggest an idea for Fundas
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
  
  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: Is your feature request related to a problem?
      placeholder: I'm frustrated when...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions you've considered?
      placeholder: I've also thought about...
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or examples
      placeholder: Here's why this would be useful...
    validations:
      required: false
